//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public Content()
        {
            this.ContentHelpSites = new HashSet<ContentHelpSite>();
            this.ContentProblems = new HashSet<ContentProblem>();
            this.ContentFiles = new HashSet<ContentFile>();
            this.Quizs = new HashSet<Quiz>();
            this.TraineeHistories = new HashSet<TraineeHistory>();
            this.TraineeQuizHistories = new HashSet<TraineeQuizHistory>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public System.Guid LevelId { get; set; }
        public int No { get; set; }
        public int Point { get; set; }
        public string Tags { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Changed { get; set; }
        public bool IsPublic { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual ICollection<ContentHelpSite> ContentHelpSites { get; set; }
        public virtual ICollection<ContentProblem> ContentProblems { get; set; }
        public virtual ICollection<ContentFile> ContentFiles { get; set; }
        public virtual ICollection<Quiz> Quizs { get; set; }
        public virtual ICollection<TraineeHistory> TraineeHistories { get; set; }
        public virtual ICollection<TraineeQuizHistory> TraineeQuizHistories { get; set; }
    }
}
