//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public Level()
        {
            this.Contents = new HashSet<Content>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int Count { get; set; }
        public int No { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Changed { get; set; }
    
        public virtual ICollection<Content> Contents { get; set; }
    }
}
