//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        public Problem()
        {
            this.ContentProblems = new HashSet<ContentProblem>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public int Complexity { get; set; }
        public int Point { get; set; }
        public int TotalSubmission { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Changed { get; set; }
    
        public virtual ICollection<ContentProblem> ContentProblems { get; set; }
    }
}
