//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public Quiz()
        {
            this.QuizQuestions = new HashSet<QuizQuestion>();
            this.TraineeQuizHistories = new HashSet<TraineeQuizHistory>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid ContentId { get; set; }
        public int Count { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Changed { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual ICollection<QuizQuestion> QuizQuestions { get; set; }
        public virtual ICollection<TraineeQuizHistory> TraineeQuizHistories { get; set; }
    }
}
