//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraineeQuizAnswerHistory
    {
        public System.Guid Id { get; set; }
        public System.Guid TraineeId { get; set; }
        public System.Guid QuizHistoryId { get; set; }
        public System.Guid QuestionId { get; set; }
        public string Answer { get; set; }
        public bool IsVerified { get; set; }
        public bool IsCorrect { get; set; }
        public System.DateTime AnswerDate { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Trainee Trainee { get; set; }
        public virtual TraineeQuizHistory TraineeQuizHistory { get; set; }
    }
}
