//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraineeQuizHistory
    {
        public TraineeQuizHistory()
        {
            this.TraineeQuizAnswerHistories = new HashSet<TraineeQuizAnswerHistory>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid TraineeId { get; set; }
        public System.Guid ContentId { get; set; }
        public System.Guid QuizId { get; set; }
        public System.DateTime Appeared { get; set; }
        public System.DateTime LastAccessed { get; set; }
        public bool IsCompleted { get; set; }
        public int CorrectAnswer { get; set; }
        public int Point { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Quiz Quiz { get; set; }
        public virtual Trainee Trainee { get; set; }
        public virtual ICollection<TraineeQuizAnswerHistory> TraineeQuizAnswerHistories { get; set; }
    }
}
