//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        public Trainee()
        {
            this.Payments = new HashSet<Payment>();
            this.TraineeHistories = new HashSet<TraineeHistory>();
            this.TraineeQuizAnswerHistories = new HashSet<TraineeQuizAnswerHistory>();
            this.TraineeQuizHistories = new HashSet<TraineeQuizHistory>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public bool IsActive { get; set; }
        public int Point { get; set; }
        public System.DateTime Joined { get; set; }
        public System.DateTime Expired { get; set; }
        public System.DateTime Changed { get; set; }
        public string Token { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<TraineeHistory> TraineeHistories { get; set; }
        public virtual ICollection<TraineeQuizAnswerHistory> TraineeQuizAnswerHistories { get; set; }
        public virtual ICollection<TraineeQuizHistory> TraineeQuizHistories { get; set; }
    }
}
